blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name="posts-index"),
    path('<slug:slug>/', PostDetailView.as_view(), name="post-detail"),
    path('<slug:slug>/new-comment', CreateCommentView.as_view(), name="comment-create"),
]

core/urls.py
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.contrib import admin

from django.urls import path, include
from blog import urls as blog_urls
from dashboard.views import ContactView
from dashboard import urls as dashboard_urls

urlpatterns = [
    path('', RedirectView.as_view(url='posts/')),
    path('admin/', admin.site.urls),
    path('posts/', include(blog_urls, namespace='blog')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('dashboard/', include(dashboard_urls, namespace='dashboard')),
    path('about/', TemplateView.as_view(template_name="blog/about.html"), name='about'),
    path('contact', ContactView.as_view(), name='contact'),
]

dashboard/urls.py
from django.urls import path, include
from dashboard.views import *

app_name = 'dashboard'
urlpatterns = [
    path('', DashboardView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category-detail'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('post-new/', PostCreateView.as_view(), name='post-new'),
    path('post-edit/<slug:slug>/', PostUpdateView.as_view(), name='post-edit'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from blog.models import Post
from .email import Email


class ContactForm(forms.Form):
    subject = forms.CharField(label="Assunto")
    email = forms.CharField(label="Email")
    message = forms.CharField(widget=forms.Textarea, label="Mensagem")

    mail = Email(
        subject=subject,
        message=message,
        receiver=email,
    )

    def send_email(self):
        if self.mail:
            return True
        
        return False


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','publish', 'category']

dashboard/views.py
from django.views.generic.list import ListView
from django.views.generic import FormView, RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView, UpdateView

from django.utils.http import is_safe_url
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.shortcuts import redirect


from blog.models import *
from .forms import PostForm, ContactForm


class ContactView(FormView):
    template_name = "blog/contact.html"
    form_class = ContactForm
    success_url = 'contact'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Contatos"
        context["form"] = ContactForm()
        return context
    
    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class LoginView(FormView):
    template_name = "dashboard/form_login.html"
    success_url = '/dashboard/'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, allowed_hosts=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):
    url = '/dashboard/login/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)



class DashboardView(ListView):
    model = Post
    template_name = "dashboard/dashboard_list.html"
    title = "Login"

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(DashboardView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Dashboard"
        context["categories"] = Category.objects.all()
        if self.request.GET.get('filter'):
            filter = self.request.GET.get('filter')
            if filter == 'published':
                context["posts"] = Post.objects.filter(
                    author__user=self.request.user,
                    publish=True,
                )
            elif filter == 'unpublished':
                context["posts"] = Post.objects.filter(
                    author__user=self.request.user,
                    publish=False,
                )
        else:
            context["posts"] = Post.objects.filter(
                author__user=self.request.user,
            )
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = "dashboard/post_detail.html"
    form_class = PostForm

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(PostDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):

        post = kwargs['object']
        context = super().get_context_data(**kwargs)
        context["title"] = post.title
        context["post"] = post
        return context


class PostCreateView(CreateView):
    model = Post
    template_name = "dashboard/post_form.html"
    fields = ['title', 'content', 'publish', 'category']
    success_url = "blog:posts"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Novo post"
        return context
    
    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(PostCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            blog_user = BlogUser.objects.get(user=request.user)
            post.author = blog_user
            post.save()
            form.save_m2m()
            return redirect('dashboard:index')


class PostUpdateView(UpdateView):
    model = Post
    fields = fields = ['title','content','publish', 'category']
    template_name = "dashboard/post_form.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Editar post: {self.object.title}"
        return context
    
    def post(self, request, *args, **kwargs):
        post = Post.objects.get(slug=kwargs.get('slug'))
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save()
            return redirect('dashboard:post-detail', post.slug)


class CategoryDetailView(DetailView):
    model = Category
    template_name = "dashboard/category_detail.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(CategoryDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = kwargs['object'].name
        context["categories"] = Category.objects.all()
        context["posts"] = Post.objects.filter(category=kwargs['object'])
        return context

templates/dashboard/layouts/base.html
{% load staticfiles %}

<!doctype html>
<html>
<head>
  <meta charset=utf-8>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <title>{{ title }} - Cultura dos bits</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Patua+One&display=swap" rel="stylesheet">
</head>
<script src="https://use.fontawesome.com/bc2794778c.js"></script>
<body>

{% include 'blog/layouts/header.html' %}

<div class="container">
  <div class="row">
    {% if request.user.is_authenticated %}
      <div class="col-sm-3">
        <div class="card sidebar">
          <div class="card-body">
            {% include "dashboard/layouts/sidebar.html" %}
          </div>
        </div>
      </div>
    {% endif %}
    {% if request.user.is_authenticated %}
      <div class="col-sm-9">
    {% else %}
      <div class="col-sm-12">
    {% endif %}
      {% block content %}

      {% endblock %}
    </div>

  </div>
</div>

<br>

{% include 'blog/layouts/footer.html' %}
<script  src="{% static 'js/jquery.js' %}"></script>
<script  src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
</body>
</html>

templates/dashboard/layouts/footer.html
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <footer class="page-footer font-small">
        <div class="footer-copyright text-center py-3 footer">
          @ 2019 Copyright
          Todos direitos reservados AlterData.com
        </div>
      </footer>
    </div>
  </div>
</div>

templates/dashboard/layouts/header.html
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <a href="{% url 'blog:posts-index' %}" class="home_link">
        <div class="jumbotron">
          <h1 class="text-center">Cultura dos bits</h1>
        </div>
      </a>
    </div>
  </div>
</div>

templates/dashboard/layouts/navbar.html
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-radius:5px;" >
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'posts-index' %}">Inicio<span class="sr-only">(página atual)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">Sobre</a>
            </li>
            <!--
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Serviços
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Ação</a>
                <a class="dropdown-item" href="#">Outra ação</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Algo mais aqui</a>
              </div>
            </li>
            -->
            <li class="nav-item">
              <a class="nav-link" href="#">Contato</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'posts-index' %}">
            <input name="search" class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Buscar</button>
          </form>
        </div>
      </nav>
    </div>
  </div>
</div>
<br>

templates/dashboard/layouts/sidebar.html
<aside class="col-12 p-0 bg-dark">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark align-items-start flex-sm-column flex-row">
        <a href class="navbar-toggler" data-toggle="collapse" data-target=".sidebar">
           <span class="navbar-toggler-icon"></span>
        </a>
        <div class="collapse navbar-collapse sidebar">
            <ul class="flex-column navbar-nav w-100 justify-content-between">
                <li class="nav-item">
                    <a class="nav-link pl-0" href="{% url 'dashboard:index' %}" aria-expanded="false">
                        <i class="fa fa-home"></i> <span class="">Home</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pl-0 dropdown-toggle text-nowrap" href="#m1" data-parent="#navbar1" data-toggle="collapse" data-target="#m1" aria-expanded="false">
                        <i class="fa fa-archive"></i> <span class="">Posts</span>
                    </a>
                    <div class="collapse" id="m1">
                        <ul class="flex-column nav">
                            <a class="nav-link px-0 text-truncate" href="{% url 'dashboard:index' %}?filter=unpublished">Arquivados</a>
                            <a class="nav-link px-0 text-truncate" href="{% url 'dashboard:index' %}?filter=published">Ativos</a>
                            <a class="nav-link px-0 text-truncate" href="{% url 'dashboard:post-new' %}">Novo</a>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link pl-0 dropdown-toggle text-nowrap" href="#m2" data-parent="#navbar1" data-toggle="collapse" data-target="#m2" aria-expanded="false">
                        <i class="fa fa-bookmark"></i> <span class=""> Categorias</span>
                    </a>
                    <div class="collapse" id="m2">
                        <ul class="flex-column nav">
                            {% for category in categories %}
                                <a class="nav-link px-0 text-truncate" href="{% url 'dashboard:category-detail' category.slug %}">{{ category.name }}</a>
                            {% endfor %}
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link pl-0" href="{% url 'dashboard:logout' %}"><i class="fa fa-times"></i> Sair</a>
                </li>
            </ul>
        </div>
    </nav>
</aside>