blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name="posts-index"),
    path('<slug:slug>/', PostDetailView.as_view(), name="post-detail"),
    path('<slug:slug>/new-comment', CreateCommentView.as_view(), name="comment-create"),
]

core/urls.py
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.contrib import admin

from django.urls import path, include
from blog import urls as blog_urls
from dashboard.views import ContactView
from dashboard import urls as dashboard_urls

urlpatterns = [
    path('', RedirectView.as_view(url='posts/')),
    path('admin/', admin.site.urls),
    path('posts/', include(blog_urls, namespace='blog')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('dashboard/', include(dashboard_urls, namespace='dashboard')),
    path('about/', TemplateView.as_view(template_name="blog/about.html"), name='about'),
    path('contact', ContactView.as_view(), name='contact'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from .constants import CHARS


class BlogUser(models.Model):
    user = models.OneToOneField(User, verbose_name="Usuário", on_delete=models.CASCADE)
    writer = models.BooleanField(default=False, verbose_name="Escritor")

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(verbose_name="Slug", unique=True, default="", editable=False, max_length=30)
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        value = self.name
        for letter in value:
            if letter in 'õãàáéíóúç':
                value = value.replace(letter, CHARS.get(letter))
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)



class Post(models.Model):
    title = models.CharField(max_length=30, verbose_name="Titulo", blank=False)
    content = models.TextField(verbose_name="Texto", blank=False)
    author = models.ForeignKey(BlogUser, on_delete=models.CASCADE, verbose_name="Autor")
    publish = models.BooleanField(verbose_name="Postado", default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    slug = models.SlugField(verbose_name="Slug", unique=True, default="", editable=False, max_length=50)
    category = models.ManyToManyField(Category, verbose_name="Categoria")

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        value = self.title
        for letter in value:
            if letter in 'ãõàáéíóúç':
                value = value.replace(letter, CHARS.get(letter))
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    email = models.EmailField(verbose_name="Email")
    content = models.TextField(verbose_name="Texto")

blog/forms.py
from django.forms import ModelForm, Textarea
from .models import Comment


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['email', 'content']
        widgets = {
            'content': Textarea(attrs={'rows':4, 'cols':15})
        }

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.db.models import Q
from .models import *
from .forms import CommentForm
from django.shortcuts import redirect



class PostListView(ListView):
    #template_name = 'blog/post_list.html'
    model = Post
    object_list = None

    def get_queryset(self):
        search = self.request.GET.get('search', None)
        c = self.request.GET.get('category', None)

        if search is not None:
            object_list = self.model.objects.filter(publish=True, slug__icontains=search)
        elif c is not None:
            category = Category.objects.get(slug=c)
            object_list = self.model.objects.filter(publish=True, category=category)
        else:
            object_list = self.model.objects.filter(publish=True)
        return object_list


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Posts"
        context["posts"] = self.object_list
        return context



class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = kwargs['object'].title
        context["comment_form"] = CommentForm()
        context["comments"] = Comment.objects.filter(post=kwargs['object'])
        return context


class CreateCommentView(CreateView):
    model = Comment
    fields = ['email', 'content']
    success_url = None

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)

        if form.is_valid():
            post = Post.objects.get(slug=kwargs.get('slug'))
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post-detail', post.slug)

templates/blog/about.html
{% extends "blog/layouts/base.html" %}
{% load static %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h3>Sobre o blog</h3>
  </div>
  <div class="card-body">
    <p>
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum 
    </p>
  </div>
</div>
{% endblock %}

templates/blog/contact.html
{% extends "blog/layouts/base.html" %}
{% load bootstrap %}
{% load static %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h3>Entre em contato</h3>
  </div>
  <div class="card-body">
    <form method="POST">
      {% csrf_token %}
      <p>
        {{ form|bootstrap }}
      </p>
      <p>
        <input value="Enviar" class="btn btn-primary" type="submit" />
      </p>
    </form>
  </div>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends "blog/layouts/base.html" %}
{% load bootstrap %}
{% load static %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h3>{{ post.title }}</h3>
    <p>{{ post.created }}</p>
    <p>
      Categorias:
      {% for c in post.category.all %}
        <a href="{% url 'blog:posts-index' %}?category={{ c.slug }}">{{ c.name }}</a>
      {% endfor %}
    </p>
  </div>
  <div class="card-body">
    <p>
      {{ post.content }}
    </p>
  </div>
  <div class="card-footer">
    <h5>Adicionar comentário</h5>
    <form method="POST" action="{% url 'blog:comment-create' post.slug %}">
      {% csrf_token %}
      {{ comment_form|bootstrap }}
      <input type="submit" value="Comentar" class="btn btn-primary" />
    </form>
  </div>
  <div class="card-footer">
    <h5>Comentários</h5>
    <hr>
    {% for comment in comments %}
      <p>
        {{ comment.email}} diz: {{ comment.content }}
      </p>
      <hr>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/blog/post_list.html
{% extends "blog/layouts/base.html" %}
{% load static %}

{% block content %}
{% if posts %}
  {% for post in posts %}
  <div class="card">
    <div class="card-header">
      <h3><a href="{% url 'blog:post-detail' post.slug %}" class="post_link">{{ post.title }}</a></h3>
    </div>
    <div class="card-body">
      <p>
        {{ post.content|truncatechars:100 }} <a href="{% url 'blog:post-detail' post.slug %}">ver mais</a>
      </p>
    </div>
  </div>
  <br>
  {% endfor %}
{% else %}
<div class="card">
  <div class="card-header">
    <h2>Sem Posts</h2>
  </div>
</div>
{% endif %}

{% endblock %}