blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name="posts-index"),
    path('<slug:slug>/', PostDetailView.as_view(), name="post-detail"),
    path('<slug:slug>/new-comment', CreateCommentView.as_view(), name="comment-create"),
]

core/urls.py
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.contrib import admin

from django.urls import path, include
from blog import urls as blog_urls
from dashboard.views import ContactView
from dashboard import urls as dashboard_urls

urlpatterns = [
    path('', RedirectView.as_view(url='posts/')),
    path('admin/', admin.site.urls),
    path('posts/', include(blog_urls, namespace='blog')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('dashboard/', include(dashboard_urls, namespace='dashboard')),
    path('about/', TemplateView.as_view(template_name="blog/about.html"), name='about'),
    path('contact', ContactView.as_view(), name='contact'),
]

dashboard/urls.py
from django.urls import path, include
from dashboard.views import *

app_name = 'dashboard'
urlpatterns = [
    path('', DashboardView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category-detail'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('post-new/', PostCreateView.as_view(), name='post-new'),
    path('post-edit/<slug:slug>/', PostUpdateView.as_view(), name='post-edit'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from blog.models import Post
from .email import Email


class ContactForm(forms.Form):
    subject = forms.CharField(label="Assunto")
    email = forms.CharField(label="Email")
    message = forms.CharField(widget=forms.Textarea, label="Mensagem")

    mail = Email(
        subject=subject,
        message=message,
        receiver=email,
    )

    def send_email(self):
        if self.mail:
            return True
        
        return False


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','publish', 'category']

dashboard/views.py
from django.views.generic.list import ListView
from django.views.generic import FormView, RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView, UpdateView

from django.utils.http import is_safe_url
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.shortcuts import redirect


from blog.models import *
from .forms import PostForm, ContactForm


class ContactView(FormView):
    template_name = "blog/contact.html"
    form_class = ContactForm
    success_url = 'contact'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Contatos"
        context["form"] = ContactForm()
        return context
    
    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class LoginView(FormView):
    template_name = "dashboard/form_login.html"
    success_url = '/dashboard/'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, allowed_hosts=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):
    url = '/dashboard/login/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)



class DashboardView(ListView):
    model = Post
    template_name = "dashboard/dashboard_list.html"
    title = "Login"

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(DashboardView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Dashboard"
        context["categories"] = Category.objects.all()
        if self.request.GET.get('filter'):
            filter = self.request.GET.get('filter')
            if filter == 'published':
                context["posts"] = Post.objects.filter(
                    author__user=self.request.user,
                    publish=True,
                )
            elif filter == 'unpublished':
                context["posts"] = Post.objects.filter(
                    author__user=self.request.user,
                    publish=False,
                )
        else:
            context["posts"] = Post.objects.filter(
                author__user=self.request.user,
            )
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = "dashboard/post_detail.html"
    form_class = PostForm

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(PostDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):

        post = kwargs['object']
        context = super().get_context_data(**kwargs)
        context["title"] = post.title
        context["post"] = post
        return context


class PostCreateView(CreateView):
    model = Post
    template_name = "dashboard/post_form.html"
    fields = ['title', 'content', 'publish', 'category']
    success_url = "blog:posts"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Novo post"
        return context
    
    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(PostCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            blog_user = BlogUser.objects.get(user=request.user)
            post.author = blog_user
            post.save()
            form.save_m2m()
            return redirect('dashboard:index')


class PostUpdateView(UpdateView):
    model = Post
    fields = fields = ['title','content','publish', 'category']
    template_name = "dashboard/post_form.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Editar post: {self.object.title}"
        return context
    
    def post(self, request, *args, **kwargs):
        post = Post.objects.get(slug=kwargs.get('slug'))
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save()
            return redirect('dashboard:post-detail', post.slug)


class CategoryDetailView(DetailView):
    model = Category
    template_name = "dashboard/category_detail.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('dashboard:login')
        return super(CategoryDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = kwargs['object'].name
        context["categories"] = Category.objects.all()
        context["posts"] = Post.objects.filter(category=kwargs['object'])
        return context

templates/dashboard/category_detail.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h3>{{ category.name.capitalize }}</h3>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Post</th><th>Data</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
          <tr>
            <td><a href="{% url 'dashboard:post-detail' post.slug %}">{{ post.title }}</a></td><td>{{ post.created }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="card-footer">

  </div>
  <div class="card-footer">

  </div>
</div>
{% endblock %}

templates/dashboard/dashboard_list.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}

{% block content %}
{% if posts %}
  <div class="card content">
    <div class="card-header">
      <h3>Lista de posts</h3>
    </div>
    <div class="card-body">
      <table class="table">
        <tr>
          <th>Título</th><th>Criado</th><th>Atualizado</th>
        </tr>
        {% for post in posts %}
          <tr>
            <td>
              <a href="{% url 'dashboard:post-detail' post.slug %}">{{ post.title }}</a>
            </td>
            <td>{{ post.created|date:"d/M/Y" }}</td>
            <td>{{ post.updated|date:"d/M/Y" }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  <br>
{% else %}
<div class="card">
  <div class="card-header">
    <h2>Sem Posts</h2>
  </div>
</div>
{% endif %}

{% endblock %}

templates/dashboard/form_login.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}
  <div class="card content">
    <div class="card-header">
      <h3 class="text-center">Painel Administrativo</h3>
    </div>
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-sm-3"></div>
          <div class="col-sm-6">
            <form class="form" method="post">
              {% csrf_token %}
              {{ form|bootstrap }}
              <div class="form-group">
                <input type="submit" value="Entrar" class="btn btn-primary">
              </div>
            </form>
          </div>
          <div class="col-sm-3"></div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/post_detail.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h3>{{ post.title }}</h3>
    <p>{{ post.created }}</p>
  </div>
  <div class="card-body">
    <p>
      {{ post.content }}
    </p>
  </div>
  <div class="card-footer">
    <p>
      Categorias:
      {% for c in post.category.all %}
        <a href="{% url 'dashboard:category-detail' c.slug %}">{{ c.name }}</a>
      {% endfor %}
    </p>
  </div>
  <div class="card-footer">
    <a href="{% url 'dashboard:post-edit' post.slug %}">
      <button class="btn btn-primary">Editar</button>
    </a>
    <button class="btn btn-danger">Deletar</button>
  </div>
</div>
{% endblock %}

templates/dashboard/post_form.html
{% extends "dashboard/layouts/base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}
<div class="card">
  <div class="card-header">
    <h3>{{ title }}</h3>
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      <p>
        {{ form | bootstrap }}
      </p>
      <p>
        <input type="submit" class="btn btn-default" value="Salvar" />
      </p>
    </form>
  </div>
  <div class="card-footer">
    <p>
      
    </p>
  </div>
  <div class="card-footer">

  </div>
</div>
{% endblock %}